// <auto-generated />
using ApiVendas.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiVendas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApiVendas.Models.Acidente", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Arma")
                        .HasColumnType("bit");

                    b.Property<bool>("Ausencia")
                        .HasColumnType("bit");

                    b.Property<bool>("Batida")
                        .HasColumnType("bit");

                    b.Property<bool>("Corte")
                        .HasColumnType("bit");

                    b.Property<bool>("Outros")
                        .HasColumnType("bit");

                    b.Property<bool>("Queda")
                        .HasColumnType("bit");

                    b.Property<int>("tExames_ID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("tAcidentes");
                });

            modelBuilder.Entity("ApiVendas.Models.PercDesconto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("tPercDesconto");
                });

            modelBuilder.Entity("ApiVendas.Models.Produto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PercDesc01")
                        .HasColumnType("int");

                    b.Property<int>("PercDesc02")
                        .HasColumnType("int");

                    b.Property<int>("PercDesc03")
                        .HasColumnType("int");

                    b.Property<int>("PercDesc04")
                        .HasColumnType("int");

                    b.Property<int>("PercDesc05")
                        .HasColumnType("int");

                    b.Property<int>("PercDesc06")
                        .HasColumnType("int");

                    b.Property<int>("PercDesc07")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("tProduto");
                });

            modelBuilder.Entity("ApiVendas.Models.Usuario", b =>
                {
                    b.Property<int>("tFuncionario_codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cargo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Inativo")
                        .HasColumnType("bit");

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Master")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("tFuncionario_codigo");

                    b.ToTable("tUsuario");
                });
#pragma warning restore 612, 618
        }
    }
}
